# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e110755fa8cfb0b0e3cfe646f97ba54015d1d37692b2066d523f0e64a83c7516f092fc4dddaf83c1f1b5cff8bf414fc91c684998718c59b44349b27b8971c06

test:
  secret_key_base: 562b779f2b9f4d032ef80e0c5e3afee364d6c8b0dd7e577437ea36646cf78063f0df1553df38b365326e89041ae21cf52e9754947bd1ce3d3333550f7c2e4875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
